// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5mxtifU_CYVNQhqBTLcsbPBQVGgrlZkY',
    appId: '1:436635449580:web:092eb429885b0a629b4dc9',
    messagingSenderId: '436635449580',
    projectId: 'cristingol-87451',
    authDomain: 'cristingol-87451.firebaseapp.com',
    storageBucket: 'cristingol-87451.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJCsuYFxrkEmRH6Qfs5lstAB3ITeROHqI',
    appId: '1:436635449580:android:579980475b30bc9c9b4dc9',
    messagingSenderId: '436635449580',
    projectId: 'cristingol-87451',
    storageBucket: 'cristingol-87451.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFur-8Sf1aM8gG4FS7C8xCK1DVoZ71nVo',
    appId: '1:436635449580:ios:04c3525235dd63c89b4dc9',
    messagingSenderId: '436635449580',
    projectId: 'cristingol-87451',
    storageBucket: 'cristingol-87451.appspot.com',
    iosClientId: '436635449580-8149mgt82dchu1kgjdvdamf3vhd965dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fakeGamesSocialmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFur-8Sf1aM8gG4FS7C8xCK1DVoZ71nVo',
    appId: '1:436635449580:ios:04c3525235dd63c89b4dc9',
    messagingSenderId: '436635449580',
    projectId: 'cristingol-87451',
    storageBucket: 'cristingol-87451.appspot.com',
    iosClientId: '436635449580-8149mgt82dchu1kgjdvdamf3vhd965dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fakeGamesSocialmedia',
  );
}
